### ISSUE TITLE
Use of redux

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#11]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/container/Dashboard.js#L9

Can we use `redux` here and write `action` and `reducer` to get user data?

**Comment by JiteshKusalkar** [comment]
Actually that form-data is temporarily being used to display content in the table. It is supposed to come from some other modules. Possibly Dashboard component will also not exist during integration.
Keeping that in mind we have implemented our code in a modular/component way so that it can be integrated with other modules easily.
